name: Run Engagement Queue
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://tweeter-khaki.vercel.app/api/twitter/runEngagementQueue' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
