name: Refresh Tokens
on:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://tweeter-khaki.vercel.app/api/twitter/refreshUserAuths' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
